package com.example.addpayinvokedemo.constant

object TransConstant {

    const val version = "version"
    const val appId = "appId"
    const val transType = "transType"
    const val businessOrderNo = "businessOrderNo"
    const val paymentType = "paymentType"
    const val amt = "amt"
    const val transData = "transData"
    const val result = "result"
    const val resultMsg = "resultMsg"
    const val paymentMethod = "paymentMethod"
    const val userID = "userID"
    const val note = "note"
    const val TID = "TID"
    const val MID = "MID"
    const val merchantName = "merchantName"
    const val transTime = "transTime"
    const val operator = "operator"
    const val batchNo = "batchNo"
    const val traceNo = "traceNo"
    const val authCode = "authCode"
    const val refNo = "refNo"
    const val cardNo = "cardNo"
    const val entryMode = "entryMode"
    const val tipAmount = "tipAmount"
    const val cardIssuerName = "cardIssuerName"
    const val cardIssuerID = "cardIssuerID"
    const val cardHolderName = "cardHolderName"
    const val expDate = "expDate"
    const val EMVApplicationID = "EMVApplicationID"
    const val EMVApplicationName = "EMVApplicationName"
    const val EMVApplicationCry = "EMVApplicationCry"
    const val EMVTerminalVerification = "EMVTerminalVerification"
    const val TSI = "TSI"
    const val ATC = "ATC"
    const val transactionID = "transactionID"
    const val originBusinessOrderNo = "originBusinessOrderNo"


}